services:
  parada_mysql:
    container_name: ContenedorGestorParada
    image: mysql:8.3.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=MicroGestorParadaDB
      - MYSQL_USERNAME=root
    ports:
      - "3309:3306"
