
services:
  mysql_monopatin:
    container_name: ContenedorMonopatin
    image: mysql:8.3.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=MicroMonopatinDB
      - MYSQL_USERNAME=root
    ports:
      - "127.0.0.1:3304:3306"

